library(shinydashboard)
library(shiny)
library(leaflet)
library(shinyjs)
library(ggplot2)
library(plotly)
library(highcharter)


dashboardPage(
              skin = 'green',
              dashboardHeader(title = 'Chen Chunxu',
                              dropdownMenu(type = "messages"),
                              dropdownMenu(type = 'notifications'),
                              dropdownMenu(type = 'tasks')),
              dashboardSidebar(
                sidebarMenu(
                  sidebarSearchForm(textId = "searchText", buttonId = "searchButton",
                                    label = "Search..."),
                  menuItem('Intro',
                           tabName = 'intro',
                           icon=icon('align-left')),
                  menuItem("Map", 
                           tabName = "Map",
                           icon = icon("map")),
                  menuItem("Charts",
                           icon=icon('bar-chart'),
                           menuItem('Panel',
                                    tabName = "Charts", 
                           icon = icon("navicon")),
                           menuItem('Control',
                                    icon=icon('th'),
                                    selectInput('select2',
                                                label='Select second Series',
                                                list('sub fields'=1,
                                                     'original place'=2),
                                                selected = 1),
                                    selectInput('select3',
                                                label='Select Year',
                                                choices = list(
                                                  '2015'=2015,'2014'=2014,
                                                  '2013'=2013,'2012'=2012,
                                                  '2011'=2011,'2010'=2010,'2009'=2009,
                                                  '2008'=2008,'2007'=2007,
                                                  '2006'=2006
                                                ),
                                                selected = 2015))),
                  menuItem('Model',
                           icon=icon('line-chart'),
                           menuItem('Regression Analysis',
                                    tabName = 'model',
                                    icon = icon('angle-double-right')),
                           menuItem('Fine Tune',
                                    icon = icon('gears'),
                                    selectInput('fit',
                                                label='Fit Type',
                                                choices = list('LM'='lm',
                                                               'GLM'='glm',
                                                               'LOESS'='loess')),
                                    selectInput('xcol',
                                                'Explanatory Variable',
                                                names(mo)[6:9],
                                                selected = names(mo)[6])
                                    ),
                           menuItem('Final Model',
                                    tabName = 'final_model',
                                    icon=icon('angle-double-right'))),
                  menuItem('Data',
                           icon = icon('table'),
                           tabName = 'table'),
                  menuItem('Conclusion',
                           tabName = 'conclusion',
                           icon=icon('file-text'))
              )),
              dashboardBody(
                tags$head(
                  useShinyjs(),
                  tags$link(rel='stylesheet',type='text/css',
                            href='IS.css')
                  # tags$script(src="JS1.js")
                ),
                tabItems(
                  tabItem(tabName ='intro',
                          box(width=10,
                              height='auto',
                              collapsed = TRUE,
                              collapsible = TRUE,
                              background = 'fuchsia',
                            title=strong('Group'),
                                img(src="group.png",
                                  height = 450,
                                  width = 750)),
                          box(width=10,
                              height='auto',
                              collapsed = TRUE,
                              collapsible = TRUE,
                              background = 'purple',
                              title=strong('Background'),
                              img(src="background.png",
                                  height = 250,
                                  width = 700)),
                          box(width=10,
                              height='auto',
                              collapsed = TRUE,
                              collapsible = TRUE,
                              background = 'maroon',
                              title=strong('Question'),
                              img(src="question.png",
                                  height = 280,
                                  width = 700)),
                          box(width=10,
                              height='auto',
                              collapsed = TRUE,
                              collapsible = TRUE,
                              background = 'red',
                              title=strong('SMART'),
                              img(src="smart.png",
                                  height = 300,
                                  width = 700))),
                  tabItem(tabName = 'Map',
                          fluidRow(
                            box(title=strong(textOutput('year')),
                                status = 'info',
                                solidHeader = TRUE,
                                # background = 'navy',
                                collapsible = TRUE,
                                width=12,
                                leafletOutput('mapcircle',
                                              height = 520),
                                absolutePanel(top=1,right=40,
                                              checkboxInput('legend',
                                                            tags$p('Show legend'
                                                                   ,class='show_legend'),
                                                            TRUE)),
                                p(),
                                sliderInput('slider',
                                            NULL,
                                            min=2006,
                                            max=2015,
                                            value=2006,
                                            step=1,
                                            sep="",
                                            animate = animationOptions(interval=800)))
                     ),
                     fluidRow(
                       box(
                         title = strong(textOutput('aspect')),
                         width=12,
                         background ='teal',
                         solidHeader = TRUE,
                         collapsible = TRUE,
                         collapsed = TRUE,
                         plotlyOutput('trends',
                                      height=600,
                                      width = '95%'),
                         absolutePanel(top=10,
                                       right=110,
                                       width =110, 
                                       selectizeInput('select1',
                                                      label=NULL,
                                                      choices=list("Amount"='amount',
                                                                   "Proportion"='proportion',
                                                                   "Rate"='increase_rate'),
                                                      selected='amount'))
            
                       )
                     )
                  ),
                  
                  tabItem(tabName = 'Charts',
                          tabsetPanel(
                            tabPanel(tags$strong('Study field'),
                                     highchartOutput('plot1',
                                                     height = 700,
                                                     width = 'auto')),
                            tabPanel(tags$strong('Institution'),
                                     highchartOutput('plot2',
                                                     height = 700,
                                                     width = 'auto')),
                            tabPanel(tags$strong('Academic level'),
                                     highchartOutput('plot3',
                                                     height=600),
                                     height=750,
                                      width='auto')
                          )),
                  tabItem(tabName = 'model',
                          fluidRow(box(title=em('Equation'),
                                       collapsible = TRUE,
                                       collapsed = TRUE,
                                       width=4,
                                       h4(strong(textOutput('model_info')))),
                                   box(title=em('Summary'),
                                              width=8,
                                              collapsible = TRUE,
                                              collapsed = TRUE,
                                              verbatimTextOutput('summary'))),
                          fluidRow(
                            box(
                              collapsible = TRUE,
                              height='100%',
                                 width=12,
                                 plotlyOutput('model',
                                              width=950,
                                              height=500),
                                 absolutePanel(
                                   left=55,top=3,
                                   checkboxInput('band',
                                              label='Band',
                                              value = TRUE)),
                                 absolutePanel(left=120,top=13,
                                               textOutput('measurement')))),
                          fluidRow(column(width=10, offset = 4,
                                          sliderInput("model_year",
                                                      label=NULL,
                                                      min = 2006,
                                                      max = 2015,
                                                      value = 2006,
                                                      step = 1,
                                                      animate = animationOptions(interval = 500),
                                                      sep='',
                                                      tick=FALSE)))),
                  tabItem(tabName = 'final_model',
                          fluidRow(box(title=em('Summary'),
                                       width=8,
                                       collapsible = TRUE,
                                       collapsed = TRUE,
                                       verbatimTextOutput('final_summary'))),
                          fluidRow(box(title=strong('Final Model'),
                                       status = 'success',
                                       # solidHeader = TRUE,
                                       height = 500,
                                       width=12,
                                       absolutePanel(top=0,
                                                     left=125,
                                                     checkboxInput('tv',
                                                                   '3D',
                                                                   value = FALSE)),
                                       plotlyOutput('fm')))),
                  tabItem(tabName = 'table',
                          tabsetPanel(
                            tabPanel(tags$strong('Model Data'),
                                     dataTableOutput('mymd'),
                                     width='auto'),
                            tabPanel(tags$strong('School'),
                                     dataTableOutput('myschool'),
                                     width='auto'),
                            tabPanel(tags$strong('Academic level'),
                                     dataTableOutput('mylevel'),
                                     width='auto')
                          )),
                  tabItem(tabName = 'conclusion',
                          box(width=9,
                              height='auto',
                              img(src="conclusion.png",
                                  height = 460,
                                  width = 730)))
                  # tabItem(tabName = 'code',
                  #         textOutput('code_text'))
                )
              )
)
